name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release ./testActions/testActions.sln
      
    - name : create publish directory
      run: mkdir -p bin/Release/netcoreapp2.2/publish   
            
    - name: dotnet publish
      run: dotnet publish -c Release ./testActions/testActions.sln
      
    - name: test variables
      run: echo ${GITHUB_WORKSPACE}
      
    - name: publish build artifacts back to GitHub
      uses: actions/upload-artifact@master
      with: 
        name: testActions
        path: testActions/bin/Release/netcoreapp2.2/publish
